### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by trbachmann** [trbachmann/byobackend#2]
- [ ] At least 2 different tables with at least 1 relationship (one-to-many or many-to-many)
- [ ] Each table has not fewer than three columns
- [ ] Postgresql database configured for development environment using knex
- [ ] Data is seeded into the database
